#!/usr/bin/env python3
"""
AiNux Demo Script
Demonstrates the capabilities of AiNux Natural Language Command Executor
"""

print("AiNux Demo - Natural Language to System Commands")
print("=" * 55)
print()
print("This script demonstrates AiNux, a Python program that converts")
print("natural language input into system commands and executes them safely.")
print()
print("Features demonstrated:")
print("✓ Natural language parsing using regex patterns")
print("✓ Cross-platform command mapping (Windows/Linux/macOS)")
print("✓ Safe command execution using subprocess")
print("✓ Security measures to block dangerous commands")
print("✓ Comprehensive error handling with timeouts")
print("✓ Interactive user interface")
print()
print("Example Commands You Can Try:")
print("-" * 30)
print("📁 File Operations:")
print("   • 'List all files in current directory'")
print("   • 'Show current working directory'")
print("   • 'Create directory myproject'")
print()
print("🖥️  System Information:")
print("   • 'Show running processes'")
print("   • 'Show network info'")
print("   • 'Show system info'")
print("   • 'Show disk usage'")
print()
print("🔒 Security Features:")
print("   • Dangerous commands are automatically blocked")
print("   • Commands timeout after 30 seconds")
print("   • Safe execution in controlled environment")
print()
print("To run AiNux interactively:")
print("   python ainux.py")
print()
print("To run AiNux with voice input (microphone):")
print("   python ainux.py --voice")
print("   Note: On Windows, install PyAudio. If 'pip install pyaudio' fails:")
print("         pip install pipwin && pipwin install pyaudio")
print()
print("For automated testing:")
print("   python test_ainux.py")
print()
print("Architecture:")
print("-" * 12)
print("🏗️  Modular design with separate components:")
print("   • Natural Language Parser")
print("   • Command Executor")
print("   • Security Module")  
print("   • Interactive Interface")
print()
print("📚 Educational Value:")
print("   • Demonstrates subprocess usage")
print("   • Shows regex pattern matching")
print("   • Illustrates security-conscious programming")
print("   • Cross-platform compatibility techniques")
print()
print("=" * 55)